# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import files_pb2 as xai_dot_api_dot_v1_dot_files__pb2


class FilesStub(object):
    """Service for uploading, listing, retrieving, and deleting files.

    Files are referenced by the `id` returned on upload (e.g. when attaching
    to chat completions). Maximum file size is 512 MB.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/xai_api.Files/UploadFile',
                request_serializer=xai_dot_api_dot_v1_dot_files__pb2.UploadFileChunk.SerializeToString,
                response_deserializer=xai_dot_api_dot_v1_dot_files__pb2.File.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/xai_api.Files/ListFiles',
                request_serializer=xai_dot_api_dot_v1_dot_files__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=xai_dot_api_dot_v1_dot_files__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.RetrieveFile = channel.unary_unary(
                '/xai_api.Files/RetrieveFile',
                request_serializer=xai_dot_api_dot_v1_dot_files__pb2.RetrieveFileRequest.SerializeToString,
                response_deserializer=xai_dot_api_dot_v1_dot_files__pb2.File.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/xai_api.Files/DeleteFile',
                request_serializer=xai_dot_api_dot_v1_dot_files__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=xai_dot_api_dot_v1_dot_files__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.RetrieveFileContent = channel.unary_stream(
                '/xai_api.Files/RetrieveFileContent',
                request_serializer=xai_dot_api_dot_v1_dot_files__pb2.RetrieveFileContentRequest.SerializeToString,
                response_deserializer=xai_dot_api_dot_v1_dot_files__pb2.FileContentChunk.FromString,
                _registered_method=True)


class FilesServicer(object):
    """Service for uploading, listing, retrieving, and deleting files.

    Files are referenced by the `id` returned on upload (e.g. when attaching
    to chat completions). Maximum file size is 512 MB.
    """

    def UploadFile(self, request_iterator, context):
        """Upload a file. The first stream message MUST set `chunk = init`
        (filename + optional TTL); subsequent messages MUST set `chunk = data`
        with file bytes in order. Recommended chunk size up to 5 MB; total
        size capped at 512 MB. Returns the new file's metadata.

        Errors: INVALID_ARGUMENT (missing/misplaced init, bad filename, bad
        TTL), RESOURCE_EXHAUSTED (over 512 MB).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """List file metadata, paginated and sorted. Returns metadata only — use
        `RetrieveFileContent` to download bytes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveFile(self, request, context):
        """Get metadata for one file. Returns metadata only — use
        `RetrieveFileContent` to download bytes. Errors NOT_FOUND if no
        accessible file with that id (including already-deleted).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Delete a file. After success it stops appearing in `ListFiles` /
        `RetrieveFile` and is no longer downloadable. Errors NOT_FOUND if no
        accessible file with that id (including already-deleted).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveFileContent(self, request, context):
        """Stream the file's contents in chunks of up to 5 MB, in order.
        Concatenate `data` from every chunk to reconstruct the file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=xai_dot_api_dot_v1_dot_files__pb2.UploadFileChunk.FromString,
                    response_serializer=xai_dot_api_dot_v1_dot_files__pb2.File.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=xai_dot_api_dot_v1_dot_files__pb2.ListFilesRequest.FromString,
                    response_serializer=xai_dot_api_dot_v1_dot_files__pb2.ListFilesResponse.SerializeToString,
            ),
            'RetrieveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveFile,
                    request_deserializer=xai_dot_api_dot_v1_dot_files__pb2.RetrieveFileRequest.FromString,
                    response_serializer=xai_dot_api_dot_v1_dot_files__pb2.File.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=xai_dot_api_dot_v1_dot_files__pb2.DeleteFileRequest.FromString,
                    response_serializer=xai_dot_api_dot_v1_dot_files__pb2.DeleteFileResponse.SerializeToString,
            ),
            'RetrieveFileContent': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveFileContent,
                    request_deserializer=xai_dot_api_dot_v1_dot_files__pb2.RetrieveFileContentRequest.FromString,
                    response_serializer=xai_dot_api_dot_v1_dot_files__pb2.FileContentChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xai_api.Files', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xai_api.Files', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Files(object):
    """Service for uploading, listing, retrieving, and deleting files.

    Files are referenced by the `id` returned on upload (e.g. when attaching
    to chat completions). Maximum file size is 512 MB.
    """

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/xai_api.Files/UploadFile',
            xai_dot_api_dot_v1_dot_files__pb2.UploadFileChunk.SerializeToString,
            xai_dot_api_dot_v1_dot_files__pb2.File.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xai_api.Files/ListFiles',
            xai_dot_api_dot_v1_dot_files__pb2.ListFilesRequest.SerializeToString,
            xai_dot_api_dot_v1_dot_files__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xai_api.Files/RetrieveFile',
            xai_dot_api_dot_v1_dot_files__pb2.RetrieveFileRequest.SerializeToString,
            xai_dot_api_dot_v1_dot_files__pb2.File.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xai_api.Files/DeleteFile',
            xai_dot_api_dot_v1_dot_files__pb2.DeleteFileRequest.SerializeToString,
            xai_dot_api_dot_v1_dot_files__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveFileContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xai_api.Files/RetrieveFileContent',
            xai_dot_api_dot_v1_dot_files__pb2.RetrieveFileContentRequest.SerializeToString,
            xai_dot_api_dot_v1_dot_files__pb2.FileContentChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
